### PR TITLE
Remove lock file

### PR DESCRIPTION
**Pull request by aminya**
This removes the security issues and the unnecessary need for continuous updating of the lock files

### CODE REVIEW

**Comment by KevinSjoberg** [comment]
@aminya I don't think this is a good idea. The `Gemfile.lock` serves a purpose. It ensures we're locked to specific versions, which is a good thing.

What problem did you try to solve?

**Comment by aminya** [comment]
> @aminya I don't think this is a good idea. The `Gemfile.lock` serves a purpose. It ensures we're locked to specific versions, which is a good thing.
> 
> What problem did you try to solve?

I am not a lock file lover. The dependencies we are using seem trustable enough that we should not need the lock file. The problem with having the lock file is that we should update the lock file itself in addition to the dependency file.

There are a couple of security issues, which might be solved by removing this.
https://github.com/atom-community/atom-community.github.io/security/dependabot

**Comment by KevinSjoberg** [comment]
@aminya in Ruby, we commit the lock file. There's good reason to do this. We can ensure everyone is running the same version of our dependencies and it allows [Bundler](https://bundler.io) to skip recalculating (potentially to something else) dependencies. Committing the `Gemfile.lock` isn't a bad thing.

If dependabot is complaining, we should update our gems, not delete `Gemfile.lock`. I'd be happy to help sort this out, if it helps. The link you posted, 404 for me.

**Comment by aminya** [comment]
No problem. I will turn on dependant bot PRs so it can update the lock file.

**Pull request closed without merging**
