### PR TITLE
wip: initial commit for rocket

### PR DESCRIPTION
**Pull request by bennypowers**
This PR implements the docs site using [rocket](https://rocket.modern-web.dev) and [11ty](https://11ty.dev)

The API docs pull in typescript definition files from [atom-ide-base](https://github.com/atom-community/atom-ide-base/tree/master/types-packages), run them through [TypeDoc](https://typedoc.org), then process the resulting "reflection JSON" with 11ty nunjucks templates and filters.

to run:

```bash
npm ci
npm run typedoc
npm start
```

## Goals
- [x] bootstrap rocket
- [x] generate docs from `.d.ts`
- [x] brand colours
- [ ] dark mode
- [ ] move more of the `<type-doc>` styles to light DOM

### CODE REVIEW

**Comment by bennypowers** [comment]
The approach I'm taking is to run typedoc in json mode against the `atom-ide-base` package, then render API docs for the types using nunjucks.

Before launching, we should update the typings in that repo to use tsdoc comments, so as to include the (markdown) descriptions in the API docs

**Comment by aminya** [comment]
This looks great so far. Thanks! 🎉

**Comment by bennypowers** [comment]
Today's progress:

Screen Shot 2021-01-24 at 17 20 53
The blurbs and screenshots here are open to changes. I was not focused on content authoring, instead on code

Screen Shot 2021-01-24 at 17 20 50
The more use we make of tsdoc in our typing files, the nicer these pages will look. All those strings come straight out of the `.d.ts`. It would be totally rad to have function parameters documented inline, as well.

**Comment by bennypowers** [comment]
Screenshot_2021-01-24 Busy Signal Atom Community

from
```ts
/**
 * `atom-ide-busy-signal` service.
 */
export interface BusySignalService {
  /**
   * Activates the busy signal with the given title and returns the promise
   * from the provided callback.
   * The busy signal automatically deactivates when the returned promise
   * either resolves or rejects.
   * @typeParam T return type of the async function
   * @param title name of the busy signal to activate
   * @param f Async function. When the promise resolves, the signal deactivates.
   * @param options options for this signal
   * @returns A promise which resolves with the type of `f`
   */
  reportBusyWhile<T>(title: string, f: () => Promise<T>, options?: BusySignalOptions): Promise<T>

  // ...
}
```

**Comment by daKmoR** [comment]
grabbing data directly from the typescript definition files sounds like a very good idea... e.g. no chance that the data get's out of sync.

Additionally the site looks nice 👍  and adding type docs will now improve typings and website at the same time... what a sweet deal 💪

Awesome progress 🎉

**Comment by illright** [comment]
Very nice looking so far. I find the red color slightly intimidating, maybe we should opt for the brown color of the logo as our accent color?

Also regarding the last screenshot of the method docs, could we write out the entire signature of the method in that blue header? I find it easier to first visually grasp the entire signature (i.e. `reportWhileBusy<T>(title: string, f: () => Promise<T>, options: BusySignalOptions`) and then read into what every parameter does.

And also it'd be great if things like `BusySignalOptions` were hyperlinks to quickly jump to the relevant interface.

Good job!

**Comment by bennypowers** [comment]
> maybe we should opt for the brown color of the logo as our accent color?

Nice idea. I haven't touched the styles that much yet.

> write out the entire signature of the method in that blue header?

Some of the signatures (e.g. the one you mentioned) can be quite long, so putting it in the header might have unintended effects on layout. WDYT about using a `<details>` element in the card body?

> hyperlinks to quickly jump to the relevant interface

[I have a plugin for this](https://github.com/apollo-elements/apollo-elements/blob/dfc2e475aadde82a21386d28e6e902047c3b34e5/rocket.config.mjs#L58-L94), but I'd prefer to implement it after solving https://github.com/modernweb-dev/rocket/issues/42. cc @daKmoR. If you all have some ideas how to solve that one, PTAL over there.

**Comment by bennypowers** [comment]
@aminya does `atom-community` have a netlify account? PR previews can facilitate discussion and development.

**Comment by illright** [comment]
> WDYT about using a `<details>` element in the card body?

Don't think it'd be as helpful but I see what you mean by the length. In that case, maybe we could omit the types and simply write out the argument names in the headers?

**Comment by aminya** [comment]
> @aminya does `atom-community` have a netlify account? PR previews can facilitate discussion and development.

I made one. However, running `pnpm install` results in an error.

**Review by aminya — APPROVED** [review]
This looks good to me.

@bennypowers Feel free to merge whenever you think this is ready

**Comment by bennypowers** [comment]
There's a few loose ends I want to tie up before merging. Asides from that the type signatures will still need some work to cover all cases, so check your expectations :D. we should iterate on more content, too.

**Comment by bennypowers** [comment]
@aminya regarding `pnpm not found` in the build, see https://answers.netlify.com/t/using-pnpm-and-pnpm-workspaces/2759

**Comment by bennypowers** [comment]
and when we merge, we should either set up the pnpm build in github pages or just use netlify to host the site

**Comment by aminya** [comment]
Can we just use Github pages? I don't see any benefits in using Netlify.

**Comment by bennypowers** [comment]
I don't mind either way, although I do like the deploy previews feature of netlify it really helps reviews

**Comment by aminya** [comment]
There is the same thing for GitHub Actions:
https://github.com/JamesIves/github-pages-deploy-action

**Pull request merged**
